[workspace]
resolver = "2"
members = [
    "exe_editor",
    "exe_game",
    "lib_game",
]

[workspace.dependencies]
bevy = { version = "0.17.2", features = ["async-io"] }
bevy_egui = { version = "0.38.1" }
toml = { version = "0.9" }

lib_game = { path = "lib_game" }
